import React from 'react';
import { SimulationStep, SensitivityResult, SiteData, ModelParams } from '../types';
import { generateCSV, generateMarkdownTable } from '../services/exportService';
import { Download, FileText, AlertTriangle, CheckCircle, Database } from 'lucide-react';

interface Props {
  site: SiteData;
  params: ModelParams;
  simData: SimulationStep[];
  sensData: SensitivityResult[];
}

const SimulationReport: React.FC<Props> = ({ site, params, simData, sensData }) => {
  if (!simData || simData.length === 0) return null;

  const initial = simData[0];
  const final = simData[simData.length - 1];
  
  const totalC_start = initial.Cveg + initial.Csoil;
  const totalC_end = final.Cveg + final.Csoil;
  const deltaC = totalC_end - totalC_start;
  const percentChange = (deltaC / totalC_start) * 100;
  
  const isSink = deltaC > 0; 
  
  const warmingTotal = final.temp - initial.temp;
  
  // Identify dominant sensitivity
  const mostSensitive = [...sensData].sort((a, b) => Math.abs(b.changeHigh) - Math.abs(a.changeHigh))[0];

  const generateMarkdown = () => {
    const date = new Date().toLocaleDateString();
    const table = generateMarkdownTable(simData, 5); // Sample every 5 years

    return `
# 森林碳循环模型评估报告
**生成日期:** ${date}
**研究站点:** ${site.Site} (${site.Lat}, ${site.Lon})

## 1. 总体结论
在 ${simData.length} 年的模拟期内，该森林生态系统表现为 **${isSink ? '碳汇 (Carbon Sink)' : '碳源 (Carbon Source)'}**。
生态系统总碳储量从 ${totalC_start.toFixed(1)} 变化至 ${totalC_end.toFixed(1)} gC/m²，变化率为 ${percentChange.toFixed(2)}%。

## 2. 情景设定
- **初始气候**: 年均温 ${site.MAT}°C, 年降雨 ${site.MAP}mm
- **气候变化**: 升温速率 ${params.warmingRate}°C/yr (总升温 ${warmingTotal.toFixed(1)}°C)
- **人类干扰**: 强度系数 h=${params.h_human} (HMI=${site.HMI})

## 3. 关键动态分析
- **植被碳库**: ${final.Cveg > initial.Cveg ? '增长' : '下降'}了 ${Math.abs(final.Cveg - initial.Cveg).toFixed(1)} gC/m²。
- **土壤碳库**: ${final.Csoil > initial.Csoil ? '增长' : '下降'}了 ${Math.abs(final.Csoil - initial.Csoil).toFixed(1)} gC/m²。
- **呼吸效应**: 期末异养呼吸(Rh)为 ${final.Rh.toFixed(1)} gC/m²/yr。

## 4. 敏感性与不确定性
系统对 **${mostSensitive.label}** 最为敏感。
当参数变动 +10% 时，最终碳储量变化约为 ${mostSensitive.changeHigh.toFixed(2)}%。
这意味着：${mostSensitive.parameter === 'Q10' ? '未来气候变暖对土壤呼吸的激发效应是决定森林碳命运的关键。' : '该参数对系统稳定性有显著控制作用。'}

## 附录：数据摘要 (每5年采样)
${table}

---
*Generated by Forest Carbon Cycle Dynamics System*
    `.trim();
  };

  const handleDownloadReport = () => {
    const blob = new Blob([generateMarkdown()], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Forest_Carbon_Report_${site.Site}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  const handleDownloadCSV = () => {
    const csv = generateCSV(simData);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Forest_Carbon_Data_${site.Site}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="max-w-4xl mx-auto bg-white p-8 rounded-lg shadow-sm border border-slate-200">
      <div className="flex justify-between items-center border-b border-slate-100 pb-6 mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">智能评估报告</h2>
          <p className="text-slate-500 text-sm mt-1">基于系统动力学模拟结果的自动解读</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={handleDownloadCSV}
            className="flex items-center gap-2 bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 px-4 py-2 rounded text-sm transition-colors shadow-sm"
          >
            <Database className="w-4 h-4" /> 下载完整数据库 (.csv)
          </button>
          <button 
            onClick={handleDownloadReport}
            className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded text-sm transition-colors shadow-sm"
          >
            <Download className="w-4 h-4" /> 下载分析文档 (.md)
          </button>
        </div>
      </div>

      <div className="space-y-8">
        
        {/* Executive Summary */}
        <section className={`p-4 rounded-lg border ${isSink ? 'bg-emerald-50 border-emerald-200' : 'bg-red-50 border-red-200'}`}>
          <div className="flex items-start gap-3">
            {isSink ? <CheckCircle className="w-6 h-6 text-emerald-600 mt-1" /> : <AlertTriangle className="w-6 h-6 text-red-600 mt-1" />}
            <div>
              <h3 className={`text-lg font-bold ${isSink ? 'text-emerald-800' : 'text-red-800'}`}>
                系统判定：{isSink ? '碳汇 (Net Sink)' : '碳源 (Net Source)'}
              </h3>
              <p className={`text-sm mt-1 ${isSink ? 'text-emerald-700' : 'text-red-700'}`}>
                在当前气候与干扰情景下，该森林生态系统{isSink ? '成功积累了碳储量' : '向大气净释放了碳'}。
                总碳库变化为 <strong>{deltaC > 0 ? '+' : ''}{deltaC.toFixed(1)} gC/m²</strong> ({percentChange.toFixed(2)}%)。
              </p>
            </div>
          </div>
        </section>

        {/* Key Metrics Grid */}
        <section>
          <h4 className="text-sm font-bold text-slate-700 uppercase tracking-wide mb-3 flex items-center gap-2">
            <FileText className="w-4 h-4" /> 关键指标变动 (Key Metrics)
          </h4>
          <div className="grid grid-cols-3 gap-4 text-sm">
            <div className="p-3 bg-slate-50 rounded border border-slate-100">
              <div className="text-slate-500 text-xs">植被碳库 (Cveg)</div>
              <div className="font-mono font-bold text-slate-800 mt-1">
                {initial.Cveg.toFixed(0)} → {final.Cveg.toFixed(0)}
              </div>
              <div className={`text-xs mt-1 ${final.Cveg >= initial.Cveg ? 'text-green-600' : 'text-red-600'}`}>
                {((final.Cveg - initial.Cveg)/initial.Cveg * 100).toFixed(1)}%
              </div>
            </div>
            <div className="p-3 bg-slate-50 rounded border border-slate-100">
              <div className="text-slate-500 text-xs">土壤碳库 (Csoil)</div>
              <div className="font-mono font-bold text-slate-800 mt-1">
                {initial.Csoil.toFixed(0)} → {final.Csoil.toFixed(0)}
              </div>
              <div className={`text-xs mt-1 ${final.Csoil >= initial.Csoil ? 'text-green-600' : 'text-red-600'}`}>
                {((final.Csoil - initial.Csoil)/initial.Csoil * 100).toFixed(1)}%
              </div>
            </div>
            <div className="p-3 bg-slate-50 rounded border border-slate-100">
              <div className="text-slate-500 text-xs">异养呼吸 (Rh)</div>
              <div className="font-mono font-bold text-slate-800 mt-1">
                {initial.Rh.toFixed(1)} → {final.Rh.toFixed(1)}
              </div>
              <div className="text-xs mt-1 text-slate-400">gC/m²/yr</div>
            </div>
          </div>
        </section>

        {/* Dynamic Interpretation */}
        <section>
          <h4 className="text-sm font-bold text-slate-700 uppercase tracking-wide mb-3">机制解读</h4>
          <div className="prose prose-sm text-slate-600 max-w-none">
            <p>
              模拟结果显示，受 <strong>{params.warmingRate > 0 ? '升温' : '气候'}</strong> 驱动，
              系统的呼吸作用（Ra + Rh）呈现 <strong>{final.Rh > initial.Rh ? '上升' : '稳定'}</strong> 趋势。
              {params.warmingRate > 0.05 && final.Rh > initial.Rh && 
                ` 特别是升温导致的 Q10 效应显著增强了土壤有机碳的分解速率，这可能是导致碳汇能力${isSink ? '减弱' : '丧失'}的主要原因。`
              }
            </p>
            <p className="mt-2">
              敏感性分析表明，系统对 <strong>{mostSensitive.label}</strong> 最为敏感。
              {mostSensitive.parameter === 'Q10' && 
                "这意味着未来气候变暖对土壤呼吸的激发效应是决定森林碳命运的关键。当 Q10 较高时，升温将导致土壤碳库快速释放，可能抵消光合作用增强带来的碳汇收益。"
              }
            </p>
          </div>
        </section>

      </div>
    </div>
  );
};

export default SimulationReport;